export const metadata = {
  manifest: "/manifest.json",
  title: "Progressive Web App",
  description: "Generated by create next app",
};
import PWAInstallPrompt from "./Component/PWAInstallPrompt";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <PWAInstallPrompt/>
      </body>
    </html>
  );
}
